name: Linux Build

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          
      - name: Install dependencies
        run: npm install
        
      - name: Install Flatpak Builder
        run: |
          sudo apt-get update && sudo apt-get install -y flatpak flatpak-builder
          sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
        
      - name: Build Linux App
        run: npm run build:linux
        
      - name: Upload Linux App (Flatpak & AppImage)
        uses: actions/upload-artifact@v4
        with:
          name: floatboard-linux-app
          path: |
            dist/linux/*.flatpak
            dist/linux/*.AppImage
